# Specifies the secret data for imagePullSecrets needed to fetch the private docker images
imageCredentials:
  create: false
  name: aqua-registry-secret # When create is false please specify
  repositoryUriPrefix: registry.aquasec.com # for dockerhub - "docker.io"
  registry: registry.aquasec.com #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""

serviceaccount:
  create: false
  name: aqua-sa

image:
  repository: "aqua-cloud-connector"
  tag: "2022.4.23preview"
  pullPolicy: "Always"

replicaCount: 1

securityContext:
  runAsUser: 11431
  runAsGroup: 11433
  fsGroup: 11433

container_securityContext:
  privileged: false

# creates admin username and password secret using below provided pain-text values.
admin:
  username: ""      # Add plain text value of the Aqua username
  password: ""      # Add plain text value of the Aqua password
# ( or )
# To load admin username and password from existing secret
adminFromSecret:
  enable: false
  secretName: ""
  userkey: ""
  passwordKey: ""

healthPort:
  port: "8080"     # default is 8080

tunnels:
  # ACR - Azure Container Registry
  azure:
    registryHost: ""
    registryPort: ""
  # ECR - Amazon Elastic Container Registry
  aws:
    registryHost: ""
    registryPort: ""
    type: ""
    region: ""
  # GCR - Google Container Registry
  gcp:
    registryHost: ""
    registryPort: ""
  # JFrog Container Registry
  jfrog:
    registryHost: ""
    registryPort: ""
  # Onprem Container Registry
  onprem:
    registryHost: ""
    registryPort: ""

gateway:
  host: "aqua-gateway-svc.aqua"   # Gateway Host Address
  port: "8443"               # Gateway Port

tls_verify:
  value: "0"    # change it to "1" to enable tls_verify b/w Gateway and Cloud-Connector

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10

nodeSelector: {}
tolerations: []
podAnnotations: {}
affinity: {}
