---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Release.Namespace }}
data:
  PGDATA: "/var/lib/postgresql/data/db-files"
  AQUA_ENV_SIZE: {{ .Values.db.env_size }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initdb-config
  namespace: {{ .Release.Namespace }}
data:
  PGDATA: "/var/lib/postgresql/data/db-files"
