{{- if .Values.envoy.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
  labels:
    app: {{ .Release.Name }}-envoy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-envoy
  template:
    metadata:
      annotations:
      {{- if and (.Values.envoy.tolerations) (semverCompare "<1.6-0" .Capabilities.KubeVersion.GitVersion) }}
        scheduler.alpha.kubernetes.io/tolerations: '{{ toJson .Values.envoy.tolerations }}'
      {{- end }}
      {{- with .Values.envoy.podAnnotations }}
      {{- range $key,$value := . }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-envoy
      name: {{ .Release.Name }}-envoy
    spec:
      securityContext:
        {{ toYaml .Values.envoy.securityContext | nindent 8 }}
      serviceAccount: {{ .Release.Namespace }}-sa
      containers:
      - image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
        imagePullPolicy: "{{ .Values.envoy.image.pullPolicy }}"
        name: envoy
        env:
        - name: ENVOY_UID
          value: "0"
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8082
          name: healthserver
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/envoy
          name: config
        {{- if .Values.envoy.TLS.listener.enabled }}
        - mountPath: /etc/ssl/envoy/listener
          name: listener-certs
        {{- end }}
        {{ if .Values.envoy.TLS.cluster.enabled }}
        - mountPath: /etc/ssl/envoy/cluster
          name: cluster-certs
        {{- end }}
{{- with .Values.envoy.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.envoy.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.envoy.resources | indent 12 }}
      {{- with .Values.envoy.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.envoy.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.envoy.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-envoy-conf
        name: config
      {{- if .Values.envoy.TLS.listener.enabled }}
      - name: listener-certs
        secret:
          defaultMode: 420
          secretName: {{ .Values.envoy.TLS.listener.secretName }}
      {{- end }}
      {{ if .Values.envoy.TLS.cluster.enabled }}
      - name: cluster-certs
        secret:
          defaultMode: 420
          secretName: {{ .Values.envoy.TLS.cluster.secretName }}
      {{- end }}
{{- end }}