{{- if .Values.envoy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-envoy-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-envoy
    aqua.component: envoy
{{ include "aqua.labels" . | indent 4 }}
data:
{{- if gt (len .Values.envoy.custom_envoy_files ) 0 }}
{{- range $key, $value := .Values.envoy.custom_envoy_files }}
  {{ $key }}: |-
{{ $valueWithDefault := default "" $value -}}
{{ tpl $valueWithDefault $ | indent 4 }}
{{- end -}}
{{- else }}
  envoy.yaml: |
{{ tpl (.Files.Get "conf/envoy.yaml.tpl") . | indent 4}}
{{- end }}
{{- end }}