{{- if .Values.web.ingress.enabled -}}
{{- $fullname := .Release.Name -}}
{{- $servicePort := (index .Values.web.service.ports 0).port -}}
{{- $ingressPath := .Values.web.ingress.path -}}
{{- $pathType := .Values.web.ingress.pathType -}}
---
{{- if .Values.web.ingress.apiVersion -}}
apiVersion: {{ .Values.web.ingress.apiVersion }}
{{- else -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-console-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-console-ingress
    aqua.component: server-ingress
{{ include "aqua.labels" . | indent 4 }}
{{- if .Values.web.ingress.annotations }}
  annotations:
{{ toYaml .Values.web.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{ if .Values.web.ingress.hosts }}
  rules:
    {{- range $host := (required "A valid .Values.web.ingress.hosts entry required!" .Values.web.ingress.hosts) }}
      - host: {{ $host }}
        http:
          paths:
            - path: {{ $ingressPath }}
              pathType: {{ $pathType }}
              backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
                service:
                  name: {{ $fullname }}-console-svc
                  port:
                    number: {{ $servicePort }}
              {{- else }}
                serviceName: {{ $fullname }}-console-svc
                servicePort: {{ $servicePort }}
              {{- end }}
    {{- end -}}
  {{ else }}
  {{- if or ($.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") (eq .Values.web.ingress.apiVersion "networking.k8s.io/v1") }}
  defaultBackend:
    service:
      name: {{ $fullname }}-console-svc
      port:
        number: {{ $servicePort }}
  {{- else }}
  backend:
    serviceName: {{ $fullname }}-console-svc
    servicePort: {{ $servicePort }}
  {{ end }}
  {{ end }}
  {{- if .Values.web.ingress.tls }}
  tls:
{{ toYaml .Values.web.ingress.tls | indent 4 }}
  {{- end -}}
  {{- end -}}