---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-console
    aqua.component: server
{{ include "aqua.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-console
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/web-configmap.yaml") . | sha256sum }}
      {{- if and (.Values.web.tolerations) (semverCompare "<1.6-0" .Capabilities.KubeVersion.GitVersion) }}
        scheduler.alpha.kubernetes.io/tolerations: '{{ toJson .Values.web.tolerations }}'
      {{- end }}
      {{- with .Values.web.podAnnotations }}
      {{- range $key,$value := . }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.vaultSecret.enabled }}
      {{- with .Values.vaultAnnotations }}
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-console
        aqua.component: server
        {{- range $key, $value := .Values.web.podLabels }}
        {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
        {{- end }}
{{ include "aqua.template-labels" . | indent 8 }}
      name: {{ .Release.Name }}-console
    spec:
      {{- with .Values.web.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      serviceAccount: {{ template "server.serviceAccount" . }}
      containers:
      - name: web
        {{- with .Values.web.container_securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        imagePullPolicy: "{{ .Values.web.image.pullPolicy }}"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-web-config
        {{- if .Values.vaultSecret.enabled }}
        command: ["/bin/sh"]
        args: ["-c", "source {{ .Values.vaultSecret.vaultFilepath }} && /web-entrypoint.sh"]
        {{- end }}
        env:
        {{- if not .Values.vaultSecret.enabled }}
        {{- if .Values.global.db.passwordFromSecret.enabled }}
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.passwordFromSecret.dbPasswordName }}
              key: {{ .Values.global.db.passwordFromSecret.dbPasswordKey }}
        {{- else }}
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              key: db-password
        {{- end }}
        - name: SCALOCK_AUDIT_DBPASSWORD
          {{- if .Values.global.db.passwordFromSecret.enabled }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.passwordFromSecret.dbAuditPasswordName }}
              key: {{ .Values.global.db.passwordFromSecret.dbAuditPasswordKey }}
          {{- else if and ( not .Values.global.db.passwordFromSecret.enabled ) ( .Values.global.db.external.enabled ) }}
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              {{- if .Values.global.db.external.auditPassword }}
              key: audit-password
              {{- else }}
              key: db-password
              {{- end }}
          {{- else }}
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              key: audit-password
          {{- end }}
          {{- if .Values.activeactive }}
          {{- if .Values.global.db.passwordFromSecret.enabled }}
        - name: AQUA_PUBSUB_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.passwordFromSecret.dbPubsubPasswordName }}
              key: {{ .Values.global.db.passwordFromSecret.dbPubsubPasswordKey }}
          {{- else }}
        - name: AQUA_PUBSUB_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              {{- if .Values.global.db.external.pubsubPassword }}
              key: pubsub-password
              {{- else }}
              key: db-password
              {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.global.db.externalDbCerts.enable }}
        - name: SSL_CERT_DIR
          value: "/etc/ext_db_certs:/etc/ssl/certs"
        {{- end }}
        {{- if or .Values.admin.token (not .Values.admin.createSecret) }}
        - name: LICENSE_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "admin.secretName" . }}
              key: license-token
        {{- end }}
        {{- if not .Values.vaultSecret.enabled }}
        {{- if or .Values.admin.password (not .Values.admin.createSecret) }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "admin.secretName" . }}
              key: admin-password
        {{- end }}
        {{- end }}
        {{- include "server.extraEnvironmentVars" .Values.web | nindent 8 }}
        {{- include "server.extraSecretEnvironmentVars" .Values.web | nindent 8 }}
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
        {{- if eq .Values.global.platform "k3s" }}
          hostPort: 8444
        {{- end }}
          protocol: TCP
{{- with .Values.web.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.web.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
        volumeMounts:
        {{- if .Values.dockerSock.mount }}
        - mountPath: /var/run/docker.sock
          name: docker-socket-mount
        {{- end }}
        {{- if .Values.web.TLS.enabled }}
        - name: certs
          mountPath: /opt/aquasec/ssl/
          readOnly: true
        {{- end }}
        {{- if .Values.global.db.externalDbCerts.enable }}
        - name: ext-db-cert
          mountPath: /etc/ext_db_certs/
          readOnly: true
        {{- end }}
        {{- include "server.additionalCertVolumeMounts" .Values | nindent 8 }}
        resources:
{{ toYaml .Values.web.resources | indent 12 }}
{{- if .Values.sidecarContainers.enabled }}
{{- toYaml .Values.sidecarContainers.ContainersDefinitions | nindent 6 }}
{{- end }}
{{- if .Values.initContainers.enabled }}
      initContainers:
{{- toYaml .Values.initContainers.ContainersDefinitions | nindent 6 }}
{{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{ toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      {{- if .Values.dockerSock.mount }}
      - name: docker-socket-mount
        hostPath:
          path: {{ .Values.dockerSock.path }}
      {{- end }}
      {{- if .Values.web.TLS.enabled }}
      - name: certs
        secret:
          defaultMode: 420
          secretName: {{ .Values.web.TLS.secretName }}
          items:
          - key: {{ .Values.web.TLS.publicKey_fileName }}
            path: cert.pem
          - key: {{ .Values.web.TLS.privateKey_fileName }}
            path: key.pem
          {{- if .Values.web.TLS.rootCA_fileName }}
          - key: {{ .Values.web.TLS.rootCA_fileName }}
            path: ca.pem
          {{- end }}
      {{- end }}
      {{- if .Values.global.db.externalDbCerts.enable }}
      - name: ext-db-cert
        secret:
          secretName: {{ .Values.global.db.externalDbCerts.certSecretName }}
      {{- end }}
      {{- include "server.additionalCertVolumes" .Values | nindent 6 }}

