apiVersion: apps/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/add-base-url: "true"
  name: aqua-console
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: csp-console-svc
          servicePort: 8080
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 192.168.27.100
