global:
  # Used for connector tunnel
  connectServerUrl: https://connect.codesec.aquasec.com
  # Used for scaning scheduling
  scanServerUrl: https://scan.codesec.aquasec.com
  # Used for scanning upstream
  aquaServerUrl: https://api.supply-chain.cloud.aquasec.com
  # Used for authentication
  cspmServerUrl: https://api.cloudsploit.com

credentials:
  createSecret: true
  secretName: aqua-codesec-secrets
  aqua_key:
  aqua_secret:

# SCM configurations:
integration:
  # Should be one of: github|gitlab_server|azure|jenkins|etc...
  source:
  url:
  username:
  password:

# Optionally add ssl ca cert and client cert/key for ssl connection to the SCM/CI server:
ssl:
  enabled: false
#  ca: |
#    -----BEGIN CERTIFICATE-----
#    ca-cert
#    -----END CERTIFICATE
#  cert: |
#    -----BEGIN CERTIFICATE-----
#    client-cert
#    -----END CERTIFICATE-----
#  key: |
#    -----BEGIN RSA PRIVATE KEY-----
#    secure key
#    -----BEGIN RSA PRIVATE KEY-----

# Proxy configurations:
proxy:
  # Specify http_proxy when you want to proxy requests that use http:// protocol
  # Example values:
  # http_proxy: http://proxy.example.com:8080
  # OR
  # http_proxy: http://admin:admin@proxy.example.com
  http_proxy:
  # Specify https_proxy when you want to proxy requests that use https:// protocol
  # Example values:
  # https_proxy: https://proxy.example.com:8080
  # OR
  # https_proxy: https://admin:admin@proxy.example.com
  https_proxy:
  # Specify no_proxy when you want to exclude specific hosts from proxying
  # You can specify multiple hosts by separating them with commas
  # Example values:
  # no_proxy: my.awesomeintegration.com
  # OR
  # no_proxy: my.awesomeintegration.com,my.awesomeservice.com
  # You can observe in this file under global key the domains that are used to communicate with the codesec servers
  no_proxy:

connect:
  image: docker.io/aquasec/codesec-connector:minified
  pullPolicy: Always
  port: 9999
  client_url:
  service:
    port: 9999
    type: ClusterIP
    annotations: {}
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  hostAliases:
  extraEnv: {}

scan:
  image: docker.io/aquasec/codesec-scanner:latest
  pullPolicy: Always
  replicas: 1
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  hostAliases:
  extraEnv: {}
