{{- if not .Values.db.external.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-database
    aqua.component: database
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      annotations:
      {{- if and (.Values.db.tolerations) (semverCompare "<1.6-0" .Capabilities.KubeVersion.GitVersion) }}
        scheduler.alpha.kubernetes.io/tolerations: '{{ toJson .Values.db.tolerations }}'
      {{- end }}
      {{- with .Values.db.podAnnotations }}
      {{- range $key,$value := . }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-database
        aqua.component: database
      name: {{ .Release.Name }}-database
    spec:
      {{- with .Values.db.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      serviceAccount: {{ .Release.Name }}-sa
      initContainers:
      - name: {{ .Release.Name }}-db-init
        env:
        {{- if .Values.db.passwordFromSecret.enabled }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.passwordFromSecret.dbPasswordName }}
              key: {{ .Values.db.passwordFromSecret.dbPasswordKey }}
        {{- else }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              key: db-password
        {{- end }}
        - name: PGDATA
          value: "/var/lib/postgresql/data/db-files"
        image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        command: [ "sh", "-c", "[ -f $PGDATA/server.key ] && chmod 600 $PGDATA/server.key || echo 'OK' " ]
        volumeMounts:
        {{- if .Values.db.persistence.enabled }}
        - mountPath: /var/lib/postgresql/data
          name: postgres-database
        {{- end }}
      containers:
      - name: db
        {{- with .Values.db.container_securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        imagePullPolicy: "{{ .Values.db.image.pullPolicy }}"
        env:
        {{- if .Values.db.passwordFromSecret.enabled }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.passwordFromSecret.dbPasswordName }}
              key: {{ .Values.db.passwordFromSecret.dbPasswordKey }}
        {{- else }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              key: db-password
        {{- end }}
        - name: PGDATA
          value: "/var/lib/postgresql/data/db-files"
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        {{- include "server.extraEnvironmentVars" .Values.db | nindent 8 }}
        {{- include "server.extraSecretEnvironmentVars" .Values.db | nindent 8 }}
        volumeMounts:
        {{- if .Values.db.persistence.enabled }}
        - mountPath: /var/lib/postgresql/data
          name: postgres-database
        {{- end }}
        ports:
        - containerPort: 5432
          protocol: TCP
{{- with .Values.db.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.db.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.db.resources | indent 10 }}
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if and (.Values.db.tolerations) (semverCompare "^1.6-0" .Capabilities.KubeVersion.GitVersion) }}
      tolerations:
{{ toYaml .Values.db.tolerations | indent 6 }}
      {{- end }}
      volumes:
      {{- if .Values.db.persistence.enabled }}
      - name: postgres-database
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-database-pvc
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-audit-database
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-audit-database
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-audit-database
  template:
    metadata:
      annotations:
      {{- if and (.Values.db.tolerations) (semverCompare "<1.6-0" .Capabilities.KubeVersion.GitVersion) }}
        scheduler.alpha.kubernetes.io/tolerations: '{{ toJson .Values.db.tolerations }}'
      {{- end }}
      {{- with .Values.db.podAnnotations }}
      {{- range $key,$value := . }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-audit-database
      name: {{ .Release.Name }}-audit-database
    spec:
      {{- with .Values.db.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      serviceAccount: {{ .Release.Name }}-sa
      initContainers:
      - name: {{ .Release.Name }}-auditdb-init
        env:
        {{- if .Values.db.passwordFromSecret.enabled }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.passwordFromSecret.dbAuditPasswordName }}
              key: {{ .Values.db.passwordFromSecret.dbAuditPasswordKey }}
        {{- else }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              key: audit-password
        {{- end }}
        - name: PGDATA
          value: "/var/lib/postgresql/data/db-files"
        image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        command: [ "sh", "-c", "[ -f $PGDATA/server.key ] && chmod 600 $PGDATA/server.key || echo 'OK' " ]
        volumeMounts:
        {{- if .Values.db.persistence.enabled }}
        - mountPath: /var/lib/postgresql/data
          name: postgres-audit-database
        {{- end }}
      containers:
      - name: auditdb
        {{- with .Values.db.container_securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        imagePullPolicy: "{{ .Values.db.image.pullPolicy }}"
        env:
        {{- if .Values.db.passwordFromSecret.enabled }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.passwordFromSecret.dbAuditPasswordName }}
              key: {{ .Values.db.passwordFromSecret.dbAuditPasswordKey }}
        {{- else }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-password
              key: audit-password
        {{- end }}
        - name: PGDATA
          value: "/var/lib/postgresql/data/db-files"
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        {{- include "server.extraEnvironmentVars" .Values.db | nindent 8 }}
        {{- include "server.extraSecretEnvironmentVars" .Values.db | nindent 8 }}
        volumeMounts:
        {{- if .Values.db.persistence.enabled }}
        - mountPath: /var/lib/postgresql/data
          name: postgres-audit-database
        {{- end }}
        ports:
        - containerPort: 5432
          protocol: TCP
{{- with .Values.db.livenessProbe }}
        livenessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.db.readinessProbe }}
        readinessProbe:
{{ toYaml . | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.db.resources | indent 10 }}
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if and (.Values.db.tolerations) (semverCompare "^1.6-0" .Capabilities.KubeVersion.GitVersion) }}
      tolerations:
{{ toYaml .Values.db.tolerations | indent 6 }}
      {{- end }}
      volumes:
      {{- if .Values.db.persistence.enabled }}
      - name: postgres-audit-database
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-audit-database-pvc
      {{- end }}
{{- end }}
