apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: {{ .Release.Name }}
    app: {{ include "kube-enforcer.fullname" . }}
    aqua.component: kubeenforcer
  name: {{ include "kube-enforcer.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "kube-enforcer.fullname" . }}
        aqua.component: kubeenforcer
    spec:
      {{- with .Values.ke.securityContext }}
      securityContext:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.ke.serviceAccount.name }}
      containers:
        - name: kube-enforcer
          {{- with .Values.ke.container_securityContext }}
          securityContext:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.ke.image.repository }}:{{ .Values.ke.image.tag }}"
          imagePullPolicy: "{{ .Values.ke.image.pullPolicy }}"
          ports:
            - containerPort: 8449
            - containerPort: 8442
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AQUA_TOKEN
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.ke.aquaSecret.name }}
                  key: token
            # Specify whether to enable/disable the cache by using "yes", "true", "no", "false" values.
            # Default value is "yes".
            - name: AQUA_ENABLE_CACHE
              value: "{{ .Values.ke.aqua_enable_cache | default "yes"}}"
            - name: AQUA_CACHE_EXPIRATION_PERIOD
              value: "{{ .Values.ke.aqua_cache_expiration_period | default "60"}}"
            - name: AQUA_LOGICAL_NAME
              value: "{{ .Values.ke.logicalName }}"
            - name: CLUSTER_NAME
              value: {{ .Values.ke.clusterName }}
            - name: TLS_SERVER_CERT_FILEPATH
              value: /certs/server.crt
            - name: TLS_SERVER_KEY_FILEPATH
              value: /certs/server.key
            - name: AQUA_GATEWAY_SECURE_ADDRESS
              value: {{ .Release.Name }}-gateway-svc:8443
            - name: AQUA_KAP_ADD_ALL_CONTROL
              value: "true"
            - name: AQUA_WATCH_CONFIG_AUDIT_REPORT
              value: "true"
            - name: AQUA_TLS_PORT
              value: "8443"
            - name: SCALOCK_LOG_LEVEL
              value: {{ .Values.ke.logLevel | default "INFO" }}
          volumeMounts:
            - name: "certs"
              mountPath: "/certs"
      volumes:
        - name: "certs"
          secret:
            secretName: {{ .Values.ke.certsSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
  selector:
    matchLabels:
      app: {{ include "kube-enforcer.fullname" . }}
