{{- if not .Values.windowsEnforcer.allWinNodes.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-enforcer-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-ds
    aqua.component: enforcer
{{ include "aqua.labels" . | indent 4 }}
data:
  {{- if .Values.multiple_gateway.enabled }}
  AQUA_SERVER: {{ join "," .Values.multi_gates }}
  {{- else }}
  AQUA_SERVER: {{ .Values.global.gateway.address | default "aqua-gateway-svc" }}:{{ .Values.global.gateway.port | default "8443" }}
  {{- end }}
  AQUA_INSTALL_PATH: "/var/lib/aquasec"
  {{- if .Values.hostRunPath }}
  AQUA_HOST_RUN_PATH: {{ .Values.hostRunPath | quote }}
  {{- end }}
  {{- if .Values.TLS.enabled }}
  AQUA_PRIVATE_KEY: "/opt/aquasec/ssl/key.pem"
  AQUA_PUBLIC_KEY: "/opt/aquasec/ssl/cert.pem"
  {{- if .Values.TLS.rootCA_fileName }}
  AQUA_ROOT_CA: "/opt/aquasec/ssl/ca.pem"
  {{- end }}
  AQUA_TLS_VERIFY: {{ .Values.TLS.tls_verify | quote }}
  {{- end }}
  AQUA_HEALTH_MONITOR_ENABLED: {{ .Values.healthMonitor.enabled | quote }}
  AQUA_EXPRESS_MODE: {{ .Values.expressMode | quote }}
{{- end }}
