---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: {{ include "kube-enforcer.fullname" . }}
  name: {{ include "kube-enforcer.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 443
      targetPort: 8443
{{- if .Values.kubeEnforcerAdvance.enable }}
      name: envoy
{{- end }}
  selector:
    app: {{ include "kube-enforcer.fullname" . }}
