---
{{- if and (ge (atoi (.Capabilities.KubeVersion.Minor | replace "+" "")) 19 ) .Values.starboard.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-starboard-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    aqua.component: starboard-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  OPERATOR_NAMESPACE: {{ .Values.starboard.OPERATOR_NAMESPACE | default .Release.Namespace}}
  OPERATOR_TARGET_NAMESPACES: "{{ .Values.starboard.OPERATOR_TARGET_NAMESPACES }}"
  OPERATOR_LOG_DEV_MODE: "{{ .Values.starboard.OPERATOR_LOG_DEV_MODE }}"
  OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT: "{{ .Values.starboard.OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT }}"
  OPERATOR_SCAN_JOB_RETRY_AFTER: "{{ .Values.starboard.OPERATOR_SCAN_JOB_RETRY_AFTER }}"
  OPERATOR_METRICS_BIND_ADDRESS: "{{ .Values.starboard.OPERATOR_METRICS_BIND_ADDRESS }}"
  OPERATOR_HEALTH_PROBE_BIND_ADDRESS: "{{ .Values.starboard.OPERATOR_HEALTH_PROBE_BIND_ADDRESS }}"
  OPERATOR_CIS_KUBERNETES_BENCHMARK_ENABLED: "{{ .Values.starboard.OPERATOR_CIS_KUBERNETES_BENCHMARK_ENABLED }}"
  OPERATOR_VULNERABILITY_SCANNER_ENABLED: "{{ .Values.starboard.OPERATOR_VULNERABILITY_SCANNER_ENABLED }}"
  OPERATOR_BATCH_DELETE_LIMIT: "{{ .Values.starboard.OPERATOR_BATCH_DELETE_LIMIT }}"
  OPERATOR_BATCH_DELETE_DELAY: "{{ .Values.starboard.OPERATOR_BATCH_DELETE_DELAY }}"
  OPERATOR_CLUSTER_COMPLIANCE_ENABLED: "{{ .Values.starboard.OPERATOR_CLUSTER_COMPLIANCE_ENABLED }}"
{{- end }}