{{- $v := .Values.connect }}
{{- $name := printf "%s-%s" (include "chart.fullname" . ) "connector" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.credentials.createSecret }}
        checksum/config: {{ include (print $.Template.BasePath "/connect/secrets.yaml") . | sha256sum }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ include "common.podLabels" . | indent 8 }}
    spec:
      {{- with .Values.connect.securityContext.pod }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.connect.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ $v.image }}
          imagePullPolicy: {{ $v.pullPolicy | default "Always" }}
          {{- with .Values.connect.securityContext.container }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          - name: SERVER_URL
            value: {{ .Values.global.connectServerUrl }}
          - name: CSPM_URL
            value: {{ .Values.global.cspmServerUrl }}
          - name: PORT
            value: {{ $v.port | quote }}
          - name: SOURCE
            value: {{ .Values.integration.source }}
          - name: SCM_URL
            value: {{ .Values.integration.url }}
          - name: BROKER_CLIENT_URL
            value: {{ $v.client_url }}
          {{- if .Values.global.brokerToken }}
          - name: BROKER_TOKEN
            value: {{ .Values.global.brokerToken }}
          {{- end }}
          {{- if .Values.global.customApiUrl }}
          - name: CUSTOM_API_URL
            value: {{ .Values.global.customApiUrl }}
          {{- end }}

          {{- if .Values.global.githubClientId }}
          - name: GITHUB_CLIENT_ID
            value: {{ .Values.global.githubClientId | quote }}
          {{- end }}
          {{- if .Values.global.githubAppId }}
          - name: GITHUB_APP_ID
            value: {{ .Values.global.githubAppId | quote }}
          {{- end }}
          {{- if .Values.global.githubSecret }}
          - name: GITHUB_SECRET
            value: {{ .Values.global.githubSecret | quote }}
          {{- end }}
          {{- if .Values.global.githubAppId }}
          - name: GITHUB_CERT_PATH
            value: /home/node/github-app.pem
          {{- end }}
          {{- if .Values.global.githubInstallationId }}
          - name: GITHUB_INSTALLATION_ID
            value: {{ .Values.global.githubInstallationId | quote }}
          {{- end }}

          {{- if .Values.ssl.enabled }}
          {{- if .Values.ssl.ca }}
          - name: CA_CERT # Path to file
            value: /home/node/ca.pem
          {{- end }}
          {{- if .Values.ssl.cert }}
          - name: HTTPS_CERT # Path to file
            value: /home/node/cert.pem
          {{- end }}
          {{- if .Values.ssl.key }}
          - name: HTTPS_KEY # Path to file
            value: /home/node/key.pem
          {{- end }}
          {{- end }}

          {{- range $key, $value := .Values.proxy }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}

          {{- range $key, $value := .Values.connect.extraEnv }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "secretName" . }}
          ports:
            - name: http
              containerPort: {{ $v.port}}
              protocol: TCP
          resources:
            {{- toYaml $v.resources | nindent 12 }}
          {{- if or (or .Values.ssl.enabled (and .Values.github .Values.github.cert)) .Values.connect.writableDirs }}
          volumeMounts:
            {{- if or .Values.ssl.enabled (and .Values.github .Values.github.cert) }}
            - name: ssl-secrets
              mountPath: "/home/node"
            {{- end }}
            {{- if .Values.connect.writableDirs }}
            {{- range .Values.connect.writableDirs }}
            - name: writable-{{ . | replace "/" "-" | replace "_" "-" | trimPrefix "-" }}
              mountPath: {{ . }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if or (or .Values.ssl.enabled (and .Values.github .Values.github.cert)) .Values.connect.writableDirs }}
      volumes:
            {{- if or .Values.ssl.enabled (and .Values.github .Values.github.cert) }}
        - name: ssl-secrets
          secret:
            secretName: {{ template "secretName" . }}
            items:
              {{- if .Values.ssl.ca }}
              - key: ssl-ca-certificate
                path: ca.pem
              {{- end }}
              {{- if .Values.ssl.cert }}
              - key: ssl-certificate
                path: cert.pem
              {{- end }}
              {{- if .Values.ssl.key }}
              - key: ssl-key
                path: key.pem
              {{- end }}
              {{- if and .Values.github .Values.github.cert }}
              - key: github-certificate
                path: github-app.pem
              {{- end }}
            {{- end }}
            {{- if .Values.connect.writableDirs }}
            {{- range .Values.connect.writableDirs }}
        - name: writable-{{ . | replace "/" "-" | replace "_" "-" | trimPrefix "-" }}
          emptyDir: {}
            {{- end }}
            {{- end }}
      {{- end }}
    {{- with $v.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $v.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $v.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
